// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         return macos;
//       case TargetPlatform.windows:
//         return windows;
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyAg4Cle203nX5G8ZUssLMDovpw41uWt-bo',
//     appId: '1:546354781705:web:cd2e4afd90781576d922d8',
//     messagingSenderId: '546354781705',
//     projectId: 'motoverse-1',
//     authDomain: 'motoverse-1.firebaseapp.com',
//     storageBucket: 'motoverse-1.firebasestorage.app',
//     measurementId: 'G-CJP0117BD4',
//   );

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyCQKbpgoXo0UDS2k08OVRPhrHoZ2IosUuk',
//     appId: '1:546354781705:android:27ba9a603d85becad922d8',
//     messagingSenderId: '546354781705',
//     projectId: 'motoverse-1',
//     storageBucket: 'motoverse-1.firebasestorage.app',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyD9aIJ0zW2xtBPyHdQSlc1Cw3z4mUcvRLA',
//     appId: '1:546354781705:ios:b5f925fd77281012d922d8',
//     messagingSenderId: '546354781705',
//     projectId: 'motoverse-1',
//     storageBucket: 'motoverse-1.firebasestorage.app',
//     iosBundleId: 'com.example.motoverse',
//   );

//   static const FirebaseOptions macos = FirebaseOptions(
//     apiKey: 'AIzaSyD9aIJ0zW2xtBPyHdQSlc1Cw3z4mUcvRLA',
//     appId: '1:546354781705:ios:b5f925fd77281012d922d8',
//     messagingSenderId: '546354781705',
//     projectId: 'motoverse-1',
//     storageBucket: 'motoverse-1.firebasestorage.app',
//     iosBundleId: 'com.example.motoverse',
//   );

//   static const FirebaseOptions windows = FirebaseOptions(
//     apiKey: 'AIzaSyAg4Cle203nX5G8ZUssLMDovpw41uWt-bo',
//     appId: '1:546354781705:web:6256bb2bfc4c4524d922d8',
//     messagingSenderId: '546354781705',
//     projectId: 'motoverse-1',
//     authDomain: 'motoverse-1.firebaseapp.com',
//     storageBucket: 'motoverse-1.firebasestorage.app',
//     measurementId: 'G-DTND8L2JER',
//   );

// }